### PR TITLE
Added zpool.iostat data collecting

### PR DESCRIPTION
**Pull request by castorsky**
Added collecting zpool iostat data (read, written bytes and read/write operations) averaged per minute

### CODE REVIEW

**Comment by AceSlash** [comment]
Very nice, you found the keys I didn't look for for the IO at `/proc/spl/kstat/zfs/pool_name/io` :-)

I have on question though: don't you think that it would be better to simply send the raw value to Zabbix and do a "Preprocessing" with "Change per second"? This would achieve the same as the mathematical operation but without the temporary file.

**Comment by castorsky** [comment]
It sure will. But preprocessing was added only at 3.4 release.
I have 5.2 server and created prototypes via `vfs.file.contents`, preprocessing and javaScript at first. But then I realized that for backward compatibility with 3.0 `bash` is the only option.

**Comment by AceSlash** [comment]
You are indeed right.

I think it's time to drop the support to version < 4.0 then. From https://www.zabbix.com/life_cycle_and_release_policy , Zabbix 3.0 will be completely unsupported next February. I don't think it's worth it to keep the compatibility for this old version since it complicate the userparameters for the newest ones.

Could you please send the version with preprocessing instead? I was about to do it myself (without the javascript), but since you already did it ;-)

**Comment by castorsky** [comment]
Successfully dropped legacy 3.0. :)

**Comment by AceSlash** [comment]
Merged, thank you for your contribution :-)

**Pull request merged**
